### ISSUE TITLE
Docs: Add `CODE_OF_CONDUCT`, `CONTRIBUTING` and `SECURITY` policies

### ISSUE THREAD

**Issue by justlevine** [rtCamp/snapwp-helper#7]
### What problem does this address?

Before making this repository public, we need to configure the following special GitHub files:

- `CODE_OF_CONDUCT.md`
- `SECURITY.md`
- `CONTRIBUTING.md`

### What is your proposed solution?

1. Add a [`CODE_OF_CONDUCT.md`](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) policy
2. Add a [`SECURITY.md`](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) policy + configure the points of contact.
3. Add a [`CONTRIBUTING.md`](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) and dedupe information from `DEVELOPMENT.md`

### Additional Context

Assumedly, *rtCamp* already has boilerplates; if necessary, we can use the policies from the rest of the WPGraphQL ecosystem for inspiration (with attribution).

```[tasklist]
### Tasks
- [ ] https://github.com/rtCamp/snapwp-helper/pull/19
- [ ] https://github.com/rtCamp/snapwp-helper/pull/18
- [ ] https://github.com/rtCamp/snapwp-helper/pull/17
```
